### ISSUE TITLE
Unknown Location on Alembic Export

### ISSUE THREAD

**Issue by tommywright** [xavier150/Blender-For-UnrealEngine-Addons#117]
I'm getting the following error in Blender (2.93) when trying to export Alembic.  I'm using your latest (3.0) version of the add-on.

Error: Python: Traceback (most recent call last):
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2449, in execute
    bfu_export_asset.ExportForUnrealEngine()
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\export\bfu_export_asset.py", line 331, in ExportForUnrealEngine
    ExportAllAssetByList(
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\export\bfu_export_asset.py", line 230, in ExportAllAssetByList
    ProcessAlembicExport(obj)
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\export\bfu_export_single_alembic_animation.py", line 58, in ProcessAlembicExport
    ExportSingleAlembicAnimation(dirpath, GetObjExportFileName(obj, ".abc"), obj)
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\export\bfu_export_single_alembic_animation.py", line 89, in ExportSingleAlembicAnimation
    VerifiDirs(absdirpath)
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_basics.py", line 270, in VerifiDirs
    os.makedirs(directory)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: 'D:\\Depot\\BlackSands_Source\\Shots\\080\\ExportedFbx\\Alembic\\Rah_PRD_RIG_v000:body_geo.001'

location: <unknown location>:-1

**Comment by xavier150** [comment]
Hey @tommywright ^^
This error is produced because the script wants to create a folder with the name "Rah_PRD_RIG_v000:body_geo.001" but ":" is an invalid character. I will work on a fix for auto remove invalid characters.

In waiting you can use rename the asset Rah_PRD_RIG_v000_body_geo.001

**Comment by tommywright** [comment]
Thank you so much for the information. I'm working with Black Sands
Entertainment and we are looking to use your amazing tool to get 7 Kingdoms
into a short film to pitch.

-Tom

**Comment by xavier150** [comment]
I just noticed that the still animation does not work very well on the last version of Blender I will try to correct this with the fix.

> Thank you so much for the information. I'm working with Black Sands Entertainment and we are looking to use your amazing tool to get 7 Kingdoms into a short film to pitch.

Oh that's awesome! It makes me very happy to know that my work is useful to you

**Comment by xavier150** [comment]
Hey @tommywright 
I just updated the last Dev Branch [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch) 
All should work now.

**Comment by tommywright** [comment]
Excellent!

**Comment by xavier150** [comment]
Hey @tommywright ^^ If all work good now you can close this issue. I will release version 0.3 in not too long I think.

**Comment by tommywright** [comment]
> Hey @tommywright ^^ If all work good now you can close this issue. I will release version 0.3 in not too long I think.

I'm still getting the same error with the dev branch version....

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2449, in execute
    bfu_export_asset.ExportForUnrealEngine()
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\export\bfu_export_asset.py", line 331, in ExportForUnrealEngine
    ExportAllAssetByList(
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\export\bfu_export_asset.py", line 230, in ExportAllAssetByList
    ProcessAlembicExport(obj)
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\export\bfu_export_single_alembic_animation.py", line 58, in ProcessAlembicExport
    ExportSingleAlembicAnimation(dirpath, GetObjExportFileName(obj, ".abc"), obj)
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\export\bfu_export_single_alembic_animation.py", line 89, in ExportSingleAlembicAnimation
    VerifiDirs(absdirpath)
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-for-unrealengine\bfu_basics.py", line 270, in VerifiDirs
    os.makedirs(directory)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: 'D:\\Depot\\BlackSands_Source\\Characters\\Rah\\ExportAlembic\\ExportedFbx\\Alembic\\Rah_PRD_RIG_v000:body_geo'

location: <unknown location>:-1

**Comment by tommywright** [comment]
Let me test it again... I'm having trouble installing this one.
