### ISSUE TITLE
v0.3.1, Blender 3.2.0, UE5 - Vertex Colors not exporting. 

### ISSUE THREAD

**Issue by insideitall89** [xavier150/Blender-For-UnrealEngine-Addons#159]
Probably because i'm using an unsupported version of blender (3.2.0)  but i'm failing to export vertex colors out of blender.

repro steps;
1. Add cube
2. Add color Attribute using default settings on pop up box
3. in 'N' panel, under Blender for Unreal Engine
4. change export type to export recursive
5. open vertex color drop down menu
6. observe warning "no vertex color found at this index"
7. export
8. observe no vertex colors when mesh imports / reimports into UE5 

![image](https://user-images.githubusercontent.com/7408609/183895347-cba6694f-b974-4914-b521-3d6a8e6ecf17.png)

**Comment by xavier150** [comment]
Hey @insideitall89
Thanks for the report! 
Indeed since Blender 3.2 Vertex Colors is refactored into generic Color Attributes.

I updated the dev branch. That should be fixed now.
You can try it? -> https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch

**Comment by insideitall89** [comment]
I tried the dev branch (4.0) was unable to export / import vertex colors using the above repro steps.

Although the error message went away.

**Comment by xavier150** [comment]
What the error message?

**Comment by insideitall89** [comment]
There is no error message now, previously in v0.3.1 it would have a warning under the vertex color dropdown that "no vertex color found at this index". now in the dev branch the message is no longer there, but vertex colors still don't export.

**Comment by xavier150** [comment]
Oh you can send me the file? I will try on my side

Le ven. 12 août 2022 à 11:14, insideitall89 ***@***.***> a
écrit :

**Comment by a1ex3d** [comment]
Dev branch seems to work for me. Just delete Vertex Color and recreate it.
